'use strict';
/**
 * monitor-anchors.js — STORY-28.3.03 / BUG-20260804-01 (the guard half).
 *
 * ---------------------------------------------------------------------------
 * What happened
 *
 * `42-Monitor/MONITOR.md` came to contain TWO COMPLETE COPIES of itself — every
 * section, header table through revision history, twice, back to back in one
 * file. It stayed that way for roughly eight phases of a thirteen-phase run.
 * Nothing noticed, because every writer and every reader of that file located
 * its section by FIRST MATCH: `text.replace(re, block)` replaces the first
 * occurrence, `/^## Revision history/` finds the first heading, and a regex with
 * no `g` flag stops at the first hit. So each writer silently picked one of the
 * two documents and wrote there. The history forked: 36 entries landed in copy
 * one, 217 in copy two, none in both. Neither copy was the record.
 *
 * The merge (2026-08-04) rebuilt one document holding the union, 253 entries,
 * none lost. This module is the other half: making the next duplication a loud
 * stop instead of a silent fork.
 *
 * ---------------------------------------------------------------------------
 * The contract
 *
 * A writer that finds TWO candidate anchors has no basis for choosing between
 * them. It must not choose. It stops, names both line numbers, and leaves the
 * file exactly as it found it — a partial write into a forked document is the
 * corruption being guarded against, not a recovery from it.
 *
 * `count === 0` is deliberately NOT this module's business. A missing marker
 * block is already `generate-monitor.js`'s own error with its own message, and a
 * MONITOR.md that has never had a revision-history heading is a different
 * problem from one that has two. This rule is about AMBIGUITY.
 *
 * ---------------------------------------------------------------------------
 * Where the anchor list comes from
 *
 * `MANAGED_KEYS` is the list `generate-monitor.js` upserts, and that script now
 * drives its own upsert loop from it — so "the anchors the writer targets" and
 * "the anchors the guard checks" are the same array rather than two lists that
 * agree today. The structural anchors are the three the incident actually forked
 * on: the revision-history heading, and the two header-table rows every close-out
 * edits by hand.
 *
 * Node stdlib only, no filesystem access: the guard is a pure function of the
 * text, which is what lets a writer check BEFORE it opens anything for writing.
 */

/** The generated marker blocks, in the order MONITOR.md carries them. */
const MANAGED_KEYS = ['overall', 'rollup', 'counts', 'wip', 'usage'];

const MARKER_BEGIN_SUFFIX = ':begin (generated by pm:monitor — do not edit by hand) -->';

/** The exact begin/end marker comments for one managed block. */
function markerBegin(key) { return '<!-- pm:monitor:' + key + MARKER_BEGIN_SUFFIX; }
function markerEnd(key) { return '<!-- pm:monitor:' + key + ':end -->'; }

function escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

/**
 * The anchors that belong to the generated blocks. One entry per marker comment:
 * a document with two `:begin` markers and one `:end` is ambiguous in a way that
 * checking only the pair as a unit would miss.
 * @param {string[]} [keys]
 */
function markerAnchors(keys) {
  const out = [];
  for (const key of (keys || MANAGED_KEYS)) {
    out.push({ name: 'pm:monitor:' + key + ':begin', re: new RegExp('^' + escapeRe(markerBegin(key))) });
    out.push({ name: 'pm:monitor:' + key + ':end', re: new RegExp('^' + escapeRe(markerEnd(key))) });
  }
  return out;
}

/**
 * The hand-written anchors. These are the ones the fork was actually written
 * through: close-out prepends under the revision-history heading, and the State /
 * Last updated rows are edited in place on every phase close.
 */
const STRUCTURAL_ANCHORS = [
  { name: '## Revision history', re: /^## Revision history\s*$/ },
  { name: '| State | header row', re: /^\| State \|/ },
  { name: '| Last updated | header row', re: /^\| Last updated \|/ },
];

/** Every anchor a MONITOR.md writer or reader resolves. */
function allAnchors(keys) {
  return markerAnchors(keys).concat(STRUCTURAL_ANCHORS);
}

/**
 * 1-based line numbers where `re` matches. Line-wise on purpose: the corpus is
 * CRLF in the working tree and LF in git, and a byte-offset answer would differ
 * between the two for the same document.
 */
function occurrences(text, re) {
  const lines = String(text === undefined || text === null ? '' : text).split(/\r?\n/);
  const hits = [];
  for (let i = 0; i < lines.length; i++) if (re.test(lines[i])) hits.push(i + 1);
  return hits;
}

/**
 * Every anchor that matches MORE THAN ONCE.
 * @returns {{name: string, lines: number[]}[]}
 */
function ambiguousAnchors(text, anchors) {
  const out = [];
  for (const a of (anchors || allAnchors())) {
    const lines = occurrences(text, a.re);
    if (lines.length > 1) out.push({ name: a.name, lines });
  }
  return out;
}

/**
 * The refusal, written out. Names EVERY line number for every ambiguous anchor —
 * "duplicated anchor" without the line numbers leaves the reader to find the
 * second copy of a 700-line document by eye, which is how the first one survived
 * eight phases.
 */
function refusalMessage(file, problems, who) {
  const lines = [];
  lines.push('✗ ' + (who || 'MONITOR writer') + ' — REFUSING to write: ' + file
    + ' has ' + problems.length + ' ambiguous anchor(s).');
  for (const p of problems) {
    lines.push('    ' + p.name + ' occurs ' + p.lines.length + ' times, at line(s) '
      + p.lines.join(' and ') + '.');
  }
  lines.push('  A writer that finds two candidate anchors has no basis for choosing one, and');
  lines.push('  choosing silently is how MONITOR.md forked into two documents for eight phases');
  lines.push('  (BUG-20260804-01: 36 revision entries in one copy, 217 in the other, none in');
  lines.push('  both). Nothing has been written. Merge the duplicated sections into one');
  lines.push('  document — keeping the UNION of the revision entries — then re-run.');
  return lines.join('\n');
}

/**
 * The guard a writer calls before it touches anything.
 * @param {string} text     the file's current contents
 * @param {Object} opts
 * @param {string} opts.file  path, for the message
 * @param {string} [opts.who] the writer's name, for the message
 * @param {Array}  [opts.anchors] defaults to every anchor
 * @returns {{ok: true} | {ok: false, problems: Array, message: string}}
 */
function assertSingleAnchors(text, opts) {
  const o = opts || {};
  const problems = ambiguousAnchors(text, o.anchors);
  if (problems.length === 0) return { ok: true };
  return { ok: false, problems, message: refusalMessage(o.file || 'MONITOR.md', problems, o.who) };
}

module.exports = {
  MANAGED_KEYS,
  markerBegin,
  markerEnd,
  markerAnchors,
  STRUCTURAL_ANCHORS,
  allAnchors,
  occurrences,
  ambiguousAnchors,
  refusalMessage,
  assertSingleAnchors,
};
