#!/usr/bin/env node
/**
 * check-mirror.js — drift validator for the kit's duplicated surfaces.
 *
 * Closes BACKLOG-0021 (root <-> scaffold mirror drift) and BACKLOG-0022
 * (ROOT-CLAUDE PM-KIT-BLOCK vs BOOTSTRAP-PROMPT.md single-source).
 *
 * Part A — every file under scaffold/_00-Project-Management/ that has a root
 *   counterpart under _00-Project-Management/ must be byte-identical (line endings
 *   normalised), EXCEPT an allow-list of files that legitimately diverge.
 * Part B — BOOTSTRAP-PROMPT.md must single-source the root CLAUDE.md block by
 *   referencing scaffold/91-Templates/ROOT-CLAUDE.template.md (so the
 *   <!-- PM-KIT-BLOCK --> body can't drift between the two).
 *
 * Usage: node _00-Project-Management/93-Scripts/check-mirror.js   (npm run pm:mirror)
 * Exit codes: 0 = no unexpected drift · 1 = drift found · 2 = script error.
 * Dependency-free — Node stdlib only (fs, path).
 */
'use strict';

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SCAFFOLD_PM = path.join(REPO_ROOT, 'scaffold', '_00-Project-Management');
const ROOT_PM = path.join(REPO_ROOT, '_00-Project-Management');

// Files (path relative to _00-Project-Management/) that legitimately differ between
// the root copy and the scaffold copy. Each MUST carry a reason — an allow-list entry
// without a documented why is how silent drift sneaks back in.
const ALLOW = {
  '42-Monitor/MONITOR.md':
    'root is this repo\'s LIVE board; scaffold ships an empty template board',
  '42-Monitor/DASHBOARD.html':
    'generated artefact — root reflects this repo\'s live data; scaffold ships a placeholder, regenerated by pm:dash on install',
  '90-Standards/CLAUDE-CODE-CONFIG.md':
    'root links repo-local ADRs (e.g. ADR-0007) that do not ship in scaffold; scaffold inlines the equivalent note',
  '93-Scripts/generate-dashboard.js':
    'root runs an enhanced dev dashboard (scans ~/.claude/ + 97-AI-Reference overlays); scaffold ships the lean portable generator — review if they should converge',
};

function normalise(s) { return s.replace(/\r\n/g, '\n'); }

function walk(dir, list = []) {
  if (!fs.existsSync(dir)) return list;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, list);
    else if (e.isFile()) list.push(full);
  }
  return list;
}

function rel(p) { return path.relative(REPO_ROOT, p).replace(/\\/g, '/'); }

function main() {
  if (!fs.existsSync(SCAFFOLD_PM)) {
    console.error(`✗ scaffold PM folder not found: ${SCAFFOLD_PM}`);
    process.exit(2);
  }

  const drift = [];
  const known = [];
  let pairs = 0;

  // ---- Part A: root <-> scaffold parity ----
  for (const sf of walk(SCAFFOLD_PM)) {
    const relUnderPm = path.relative(SCAFFOLD_PM, sf).replace(/\\/g, '/');
    const rf = path.join(ROOT_PM, relUnderPm);
    if (!fs.existsSync(rf)) continue; // scaffold-only file — no mirror obligation
    pairs += 1;
    const same = normalise(fs.readFileSync(rf, 'utf8')) === normalise(fs.readFileSync(sf, 'utf8'));
    if (same) continue;
    if (relUnderPm in ALLOW) known.push({ file: relUnderPm, reason: ALLOW[relUnderPm] });
    else drift.push(relUnderPm);
  }

  // ---- Part B: BOOTSTRAP single-sources the ROOT-CLAUDE block (BACKLOG-0022) ----
  const bootstrap = path.join(REPO_ROOT, 'BOOTSTRAP-PROMPT.md');
  const tmpl = path.join(REPO_ROOT, 'scaffold', '91-Templates', 'ROOT-CLAUDE.template.md');
  let bootstrapNote = '';
  if (!fs.existsSync(bootstrap)) {
    drift.push('BOOTSTRAP-PROMPT.md (missing — paste-prompt installer expected at repo root)');
  } else {
    const b = fs.readFileSync(bootstrap, 'utf8');
    if (!/ROOT-CLAUDE\.template\.md/.test(b)) {
      drift.push('BOOTSTRAP-PROMPT.md does not reference ROOT-CLAUDE.template.md — PM-KIT-BLOCK is no longer single-sourced (BACKLOG-0022 drift risk)');
    } else if (fs.existsSync(tmpl) && !/<!--\s*PM-KIT-BLOCK\s*-->/.test(fs.readFileSync(tmpl, 'utf8'))) {
      drift.push('ROOT-CLAUDE.template.md is missing the <!-- PM-KIT-BLOCK --> marker BOOTSTRAP relies on');
    } else {
      bootstrapNote = 'BOOTSTRAP-PROMPT.md single-sources the PM-KIT-BLOCK from ROOT-CLAUDE.template.md ✓';
    }
  }

  // ---- Report ----
  for (const k of known) console.log(`  known divergence (allow-listed): ${k.file} — ${k.reason}`);
  if (bootstrapNote) console.log(`  ${bootstrapNote}`);

  if (drift.length === 0) {
    console.log(`✓ pm:mirror — ${pairs} mirrored pair(s) checked, ${known.length} known divergence(s), 0 unexpected drift.`);
    process.exit(0);
  }
  console.log(`\n✗ pm:mirror — ${drift.length} unexpected drift(s):`);
  for (const d of drift) console.log(`    - ${d}`);
  console.log(`\nFix: sync the root and scaffold copies, or (if the divergence is intentional) add the file to the ALLOW list in check-mirror.js with a reason.`);
  process.exit(1);
}

main();
