#!/usr/bin/env node
/**
 * check-mirror.js — drift validator for the kit's duplicated surfaces.
 *
 * Closes BACKLOG-0021 (root <-> scaffold mirror drift) and BACKLOG-0022
 * (ROOT-CLAUDE PM-KIT-BLOCK vs BOOTSTRAP-PROMPT.md single-source).
 *
 * Part A — every file under scaffold/_00-Project-Management/ that has a root
 *   counterpart under _00-Project-Management/ must be byte-identical (line endings
 *   normalised), EXCEPT an allow-list of files that legitimately diverge.
 * Part B — BOOTSTRAP-PROMPT.md must single-source the root CLAUDE.md block by
 *   referencing scaffold/91-Templates/ROOT-CLAUDE.template.md (so the
 *   <!-- PM-KIT-BLOCK --> body can't drift between the two).
 *
 * Usage: node _00-Project-Management/93-Scripts/check-mirror.js   (npm run pm:mirror)
 * Exit codes: 0 = no unexpected drift · 1 = drift found · 2 = script error.
 * Dependency-free — Node stdlib only (fs, path).
 */
'use strict';

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const SCAFFOLD_PM = path.join(REPO_ROOT, 'scaffold', '_00-Project-Management');
const ROOT_PM = path.join(REPO_ROOT, '_00-Project-Management');

// The set of mirror-class folders in _00-Project-Management/ that check-mirror
// tracks for parity in BOTH directions (scaffold→root AND root→scaffold).
const MIRROR_DIRS = ['90-Standards', '91-Templates', '92-Prompts', '93-Scripts'];

// Files (path relative to _00-Project-Management/) that legitimately differ between
// the root copy and the scaffold copy. Each MUST carry a reason — an allow-list entry
// without a documented why is how silent drift sneaks back in.
const ALLOW = {
  '12-Active/ACTIVE.md':
    'root is this repo\'s LIVE WIP index; scaffold ships an empty template ACTIVE board (BUG-20260601-01)',
  '90-Standards/PROJECT-CONTEXT.md':
    'root is this repo\'s filled-in stack/gotchas (dogfood); scaffold ships the placeholder template projects fill in (BUG-20260601-01)',
  '42-Monitor/MONITOR.md':
    'root is this repo\'s LIVE board; scaffold ships an empty template board',
  '42-Monitor/DASHBOARD.html':
    'generated artefact — root reflects this repo\'s live data; scaffold ships a placeholder, regenerated by pm:dash on install',
  '90-Standards/CLAUDE-CODE-CONFIG.md':
    'root links repo-local ADRs (e.g. ADR-0007) that do not ship in scaffold; scaffold inlines the equivalent note',
  '93-Scripts/package.json':
    'root is the kit itself; scaffold is a reference document for the PM folder that projects integrate; served from different package.json contexts',
  '93-Scripts/smoke-dashboard.js':
    'root-only; dev smoke test for the live dashboard generator (scaffold ships the lean portable generator)',
  '93-Scripts/test-monitor-parser.js':
    'root-only; dev self-test for the monitor parser R20 detection (STORY-13.2.01) — scaffold ships the parser, not the test',
  '93-Scripts/test-pm-paths.js':
    'root-only; dev self-test for the pm-paths resolver (FEAT-12.1) — scaffold ships the resolver, not the test',
  '93-Scripts/__fixtures__':
    'root-only; dev test fixtures for CLI validators, not shipped to deployed projects',
  '93-Scripts/generate-dashboard.js':
    'root runs an enhanced dev dashboard (scans ~/.claude/ + 97-AI-Reference overlays); scaffold ships the lean portable generator — review if they should converge',
};

function normalise(s) { return s.replace(/\r\n/g, '\n'); }

function walk(dir, list = []) {
  if (!fs.existsSync(dir)) return list;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, list);
    else if (e.isFile()) list.push(full);
  }
  return list;
}

function rel(p) { return path.relative(REPO_ROOT, p).replace(/\\/g, '/'); }

function main() {
  if (!fs.existsSync(SCAFFOLD_PM)) {
    console.error(`✗ scaffold PM folder not found: ${SCAFFOLD_PM}`);
    process.exit(2);
  }

  const drift = [];
  const known = [];
  let pairs = 0;

  // ---- Part A: root <-> scaffold parity (scaffold→root: scaffold files must have a root counterpart or be scaffold-only) ----
  for (const sf of walk(SCAFFOLD_PM)) {
    const relUnderPm = path.relative(SCAFFOLD_PM, sf).replace(/\\/g, '/');
    const rf = path.join(ROOT_PM, relUnderPm);
    if (!fs.existsSync(rf)) continue; // scaffold-only file — no mirror obligation
    pairs += 1;
    const same = normalise(fs.readFileSync(rf, 'utf8')) === normalise(fs.readFileSync(sf, 'utf8'));
    if (same) continue;
    if (relUnderPm in ALLOW) known.push({ file: relUnderPm, reason: ALLOW[relUnderPm] });
    else drift.push(relUnderPm);
  }

  // ---- Part A (reverse): root→scaffold parity (for mirror-class folders only) ----
  // Walk only the mirror-class folders (90-Standards/, 91-Templates/, etc.) under ROOT_PM
  // to detect root-only files that should ship to scaffold. Work-artefact folders
  // (10-Inbox, 12-Active, 32-Stories, etc.) are deliberately out of scope.
  function isAllowed(relPath) {
    // Check exact match first
    if (relPath in ALLOW) return true;
    // Check if it's under an allowed directory (e.g. __fixtures__)
    for (const key of Object.keys(ALLOW)) {
      if (relPath.startsWith(key + '/') || relPath === key) return true;
    }
    return false;
  }
  for (const mirrorDir of MIRROR_DIRS) {
    const rootMirrorPath = path.join(ROOT_PM, mirrorDir);
    if (!fs.existsSync(rootMirrorPath)) continue;
    for (const rf of walk(rootMirrorPath)) {
      const relUnderMirrorDir = path.relative(rootMirrorPath, rf).replace(/\\/g, '/');
      const relUnderPm = mirrorDir + '/' + relUnderMirrorDir;
      const sf = path.join(SCAFFOLD_PM, relUnderPm);
      if (fs.existsSync(sf)) continue; // scaffold counterpart exists — no drift
      // root-only file in a mirror-class folder with no scaffold counterpart
      if (isAllowed(relUnderPm)) known.push({ file: relUnderPm, reason: ALLOW[Object.keys(ALLOW).find(k => relUnderPm === k || relUnderPm.startsWith(k + '/'))] || '(parent allowed)' });
      else drift.push('(root-only) ' + relUnderPm);
    }
  }

  // ---- Part B: BOOTSTRAP single-sources the ROOT-CLAUDE block (BACKLOG-0022) ----
  const bootstrap = path.join(REPO_ROOT, 'BOOTSTRAP-PROMPT.md');
  const tmpl = path.join(REPO_ROOT, 'scaffold', '91-Templates', 'ROOT-CLAUDE.template.md');
  let bootstrapNote = '';
  if (!fs.existsSync(bootstrap)) {
    drift.push('BOOTSTRAP-PROMPT.md (missing — paste-prompt installer expected at repo root)');
  } else {
    const b = fs.readFileSync(bootstrap, 'utf8');
    if (!/ROOT-CLAUDE\.template\.md/.test(b)) {
      drift.push('BOOTSTRAP-PROMPT.md does not reference ROOT-CLAUDE.template.md — PM-KIT-BLOCK is no longer single-sourced (BACKLOG-0022 drift risk)');
    } else if (fs.existsSync(tmpl) && !/<!--\s*PM-KIT-BLOCK\s*-->/.test(fs.readFileSync(tmpl, 'utf8'))) {
      drift.push('ROOT-CLAUDE.template.md is missing the <!-- PM-KIT-BLOCK --> marker BOOTSTRAP relies on');
    } else {
      bootstrapNote = 'BOOTSTRAP-PROMPT.md single-sources the PM-KIT-BLOCK from ROOT-CLAUDE.template.md ✓';
    }
  }

  // ---- Report ----
  for (const k of known) console.log(`  known divergence (allow-listed): ${k.file} — ${k.reason}`);
  if (bootstrapNote) console.log(`  ${bootstrapNote}`);

  if (drift.length === 0) {
    console.log(`✓ pm:mirror — ${pairs} mirrored pair(s) checked, ${known.length} known divergence(s), 0 unexpected drift.`);
    process.exit(0);
  }
  console.log(`\n✗ pm:mirror — ${drift.length} unexpected drift(s):`);
  for (const d of drift) console.log(`    - ${d}`);
  console.log(`\nFix: sync the root and scaffold copies, or (if the divergence is intentional) add the file to the ALLOW list in check-mirror.js with a reason.`);
  process.exit(1);
}

main();
